urls:
  pc: "https://dream.onuri.co.kr/main"       # PC 테스트 URL
  mobile: "https://mdream.onuri.co.kr/main"  # 모바일 테스트 URL

search:
  valid:
    - 생수
    - 수건
    - 물
    - 닭가슴살
    - 텀블러
    - 이어폰
    - 휴대폰
    - 신발
    - 핸드폰
    - 게임
    - 옷
    - 크림
    - 우산
    - 백팩
    - 충전기
    - 노트북
    - 노이즈 캔슬링
    - 치약

categories:
  pool:
    - 가전/디지털
    - 식품
    - 뷰티
    - 생활/건강
    - 가구/인테리어
    - 스포츠/레저/자동차
    - 잡화
    - 문구/취미/펫
  count: 5

dooray:
  bot_name: "드림몰 테스트봇"