malls:
  - name: "드림몰"
    id: dream
    urls:
      pc: "https://dream.onuri.co.kr/main"
      mobile: "https://mdream.onuri.co.kr/main"
    requires_login: true
    categories:
      - 가구/인테리어
      - 가전/디지털
      - 문구/취미/펫
      - 뷰티
      - 생활/건강
      - 스포츠/레저/자동차
      - 식품
      - 잡화


  - name: "행정공제회(poba)"
    id: poba
    urls:
      pc: "https://www.pobaonuri.kr/"
      mobile: "https://m.pobaonuri.kr/"
    login_url: "https://www.pobaonuri.kr/indexLogin"
    requires_login: true
    categories:
      - 가구/인테리어
      - 가전/디지털
      - 문구/취미/펫
      - 뷰티
      - 생활/건강
      - 스포츠/레저/자동차
      - 식품
      - 의류
      - 잡화
      - 출산/육아

  - name: "삼아(samaint)"
    id: sama
    urls:
      pc: "https://samaint.onuri.co.kr/"
      mobile: "https://msamaint.onuri.co.kr/"
    requires_login: true
    categories:
      - 가구/인테리어
      - 가전/디지털
      - 문구/취미/펫
      - 뷰티
      - 생활/건강
      - 스포츠/레저/자동차
      - 식품
      - 의류
      - 잡화
      - 출산/육아

  - name: "교직원공제회(thek)"
    id: thek
    urls:
      pc: "https://thek.onuri.co.kr/"
      mobile: "https://mthek.onuri.co.kr/"
    requires_login: true
    categories:
      - 가구/인테리어
      - 가전/디지털
      - 문구/취미/펫
      - 뷰티
      - 생활/건강
      - 스포츠/레저/자동차
      - 식품
      - 의류
      - 잡화
      - 출산/육아

  - name: "welfare(castdream)"
    id: castdream
    urls:
      pc: "https://mcastdream.onuri.co.kr/"
      mobile: "https://castdream.onuri.co.kr/"
    requires_login: false
    skip: true
    categories:
      - 가구/인테리어
      - 가전/디지털
      - 문구/취미/펫
      - 뷰티
      - 생활/건강
      - 스포츠/레저/자동차
      - 식품
      - 의류
      - 잡화
      - 출산/육아

search:
  valid:
    - 생수
    - 수건
    - 물
    - 닭가슴살
    - 텀블러
    - 이어폰
    - 신발
    - 케이스
    - 옷
    - 크림
    - 우산
    - 가방
    - 찌개
    - 고기
    - 떡
    - 김치
    - 치약

categories:
  pool:
    - 가전/디지털
    - 식품
    - 뷰티
    - 생활/건강
    - 가구/인테리어
    - 스포츠/레저/자동차
    - 잡화
    - 문구/취미/펫
  count: 5

dooray:
  bot_name: "드림몰 테스트봇"
